package CASTRO_TOCAFFONDI;

import java.awt.Color;
import java.util.Arrays;
//import CASTRO_TOCAFFONDI.Grafico;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author CASTRO TOCAFFONDI
 */
public class Prueba extends javax.swing.JFrame {
    /**
     * Creates new form Prueba
     */
    public Prueba() {
        initComponents();
        //Color JFrame
        this.getContentPane().setBackground(new Color(59,60,54));
        //Color de los Paneles
        //jPanel1.setBackground(new Color(0,0,0,0));
        setLocationRelativeTo(null);
        this.setResizable(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jOrigen = new javax.swing.JComboBox<>();
        jDestino = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jtbtnRuta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Grafos aplicado en aerolineas");

        jButton1.setText("Ver destinos disponibles");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Selecciona tu ubicacion actual");

        jOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[Seleccionar ubicacion]", "A", "B", "C", "D", "E", "F", "H" }));
        jOrigen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOrigenActionPerformed(evt);
            }
        });

        jDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[Seleccionar destino]", "A", "B", "C", "D", "E", "F", "H" }));
        jDestino.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDestinoActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Seleccionar el pais al cual desea viajar");

        jtbtnRuta.setText("Ver la ruta más corta");
        jtbtnRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbtnRutaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jtbtnRuta))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jButton1)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jButton1)
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jtbtnRuta)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Grafico g=new Grafico();
        g.addVertice("A", Arrays.asList(new Vertice("B", 7), new Vertice("C", 8)));
	g.addVertice("B", Arrays.asList(new Vertice("A", 7), new Vertice("F", 2)));
	g.addVertice("C", Arrays.asList(new Vertice("A", 8), new Vertice("F", 6), new Vertice("G", 4)));
	g.addVertice("D", Arrays.asList(new Vertice("F", 8)));
	g.addVertice("E", Arrays.asList(new Vertice("H", 1)));
	g.addVertice("F", Arrays.asList(new Vertice("B", 2), new Vertice("C", 6), new Vertice("D", 8), new Vertice("G", 9), new Vertice("H", 3)));
	g.addVertice("G", Arrays.asList(new Vertice("C", 4), new Vertice("F", 9)));
	g.addVertice("H", Arrays.asList(new Vertice("E", 1), new Vertice("F", 3)));
        JOptionPane.showMessageDialog(null,"Los destinos disponibles son:\n"+g.Mostrar(null, null),"Destinos disponibles",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jOrigenActionPerformed

    private void jDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDestinoActionPerformed

    private void jtbtnRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbtnRutaActionPerformed
        // TODO add your handling code here:
        Grafico g=new Grafico();
        g.addVertice("A", Arrays.asList(new Vertice("B", 7), new Vertice("C", 8)));
	g.addVertice("B", Arrays.asList(new Vertice("A", 7), new Vertice("F", 2)));
	g.addVertice("C", Arrays.asList(new Vertice("A", 8), new Vertice("F", 6), new Vertice("G", 4)));
	g.addVertice("D", Arrays.asList(new Vertice("F", 8)));
	g.addVertice("E", Arrays.asList(new Vertice("H", 1)));
	g.addVertice("F", Arrays.asList(new Vertice("B", 2), new Vertice("C", 6), new Vertice("D", 8), new Vertice("G", 9), new Vertice("H", 3)));
	g.addVertice("G", Arrays.asList(new Vertice("C", 4), new Vertice("F", 9)));
	g.addVertice("H", Arrays.asList(new Vertice("E", 1), new Vertice("F", 3)));
        if(jOrigen.getSelectedItem().equals("[Seleccionar origen]")||jDestino.getSelectedItem().equals("[Seleccionar destino]")){
            JOptionPane.showMessageDialog(null,"No ha seleccionado correctamente","Error",JOptionPane.ERROR_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null,"El trayecto mas optimo pasa por "+g.Mostrar((String) jDestino.getSelectedItem(), (String) jOrigen.getSelectedItem())+" para llegar a "+jDestino.getSelectedItem(),"Mostrar la ruta más corta",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jtbtnRutaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jDestino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> jOrigen;
    private javax.swing.JButton jtbtnRuta;
    // End of variables declaration//GEN-END:variables
}
